[update]
tasks = ["interfaces", "transform", "normalize"]

[update.interfaces]
path = "./{{ cookiecutter.name }}/Resources/Storyboards"
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.transform]
codePath = "./{{ cookiecutter.name }}/Classes"
localizablePath = "./{{ cookiecutter.name }}/Resources"
transformer = "swiftgenStructured"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "./{{ cookiecutter.name }}/Resources"
sourceLocale = "ru"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "."
duplicateKeys = true
emptyValues = true
