[tasks]
pre-commit = "swiftformat {{ cookiecutter.name }} {{ cookiecutter.name }}Tests --lint"
fmt = "swiftformat {{ cookiecutter.name }} {{ cookiecutter.name }}Tests"
project = "xcodegen"

[tools]
swiftformat = "latest"
xcodegen = "2.38.0"
