[tasks]
pre-commit = "swiftformat {{ cookiecutter.name }} {{ cookiecutter.name }}Tests --lint"
fmt = "swiftformat {{ cookiecutter.name }} {{ cookiecutter.name }}Tests"

[tools]
xcodes = "1.5.0"
swiftformat = "0.54.6"
xcodegen = "latest"
