repos:
-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.35.7
    hooks:
    -   id: swiftformat
        exclude: (Carthage|{{ cookiecutter.name }}/Classes/UIKit/Extensions/Images.swift|{{ cookiecutter.name }}/Classes/UIKit/Extensions/Strings.swift)
