repos:
-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.39.0
    hooks:
    -   id: swiftformat
        exclude: (Carthage|{{ cookiecutter.name }}/Classes/Generated)
        args: [--config, .swiftformat]
