excluded:
  - Carthage
  - {{ cookiecutter.name }}/Classes/UIKit/Extensions/Images.swift
  - {{ cookiecutter.name }}/Classes/UIKit/Extensions/Strings.swift

disabled_rules:
  - trailing_comma

opt_in_rules:
  - array_init
  - empty_string
  - untyped_error_in_catch
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - fallthrough
  - empty_xctest_method
  - file_name
  - convenience_type

line_length: 140
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 24
    error: 32
cyclomatic_complexity:
  error: 30
