#!usr/bin/ruby

commit_lint.check warn: :all

swiftlint.lint_files

xcode_summary.ignored_files = '**/Carthage/**'
xcode_summary.report 'build/reports/errors.json'

synx.no_sort_by_name = true
synx.ensure_clean_structure

ios_logs.check

cartfile_updated = !git.modified_files.grep(/Cartfile/).empty?
cartfile_resolved_updated = !git.modified_files.grep(/Cartfile.resolved/).empty?

if cartfile_updated
    message('PR change a list of dependencies')
    if !cartfile_resolved_updated
        fail('The Cartfile.resolved is not sync')
    end
end

the_coding_love.random
