name: {{ cookiecutter.name }}
options:
  developmentLanguage: ru
  knownRegions: ["ru", "Base"]
  createIntermediateGroups: true
attributes:
  ORGANIZATIONNAME: {{ cookiecutter.organization }}
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: ./{{ cookiecutter.name }}/Resources/Configuration/Debug.xcconfig
  Release: ./{{ cookiecutter.name }}/Resources/Configuration/Release.xcconfig
targets:
  {{ cookiecutter.name | lower }}:
    type: application
    platform: iOS
    configFiles:
      Debug: ./{{ cookiecutter.name }}/Resources/Configuration/Debug-App.xcconfig
      Release: ./{{ cookiecutter.name }}/Resources/Configuration/Release-App.xcconfig
    sources:
      - path: {{ cookiecutter.name }}
    scheme:
      testTargets:
        - {{ cookiecutter.name | lower }}Tests
    attributes:
      ProvisioningStyle: Automatic
      DevelopmentTeam: {{ cookiecutter.development_team_id }}
  {{ cookiecutter.name | lower }}Tests:
    type: bundle.unit-test
    platform: iOS
    configFiles:
      Debug: ./{{ cookiecutter.name }}/Resources/Configuration/Debug-Tests.xcconfig
      Release: ./{{ cookiecutter.name }}/Resources/Configuration/Release-Tests.xcconfig
    sources:
      - {{ cookiecutter.name }}
      - {{ cookiecutter.name }}Tests
    dependencies:
      - target: {{ cookiecutter.name | lower }}
