name: {{ cookiecutter.name }}
options:
  postGenCommand: "make pods"
  deploymentTarget:
    iOS: {{ cookiecutter.deployment_target }}
  developmentLanguage: ru
  knownRegions: ["ru", "Base"]
  createIntermediateGroups: true
attributes:
  ORGANIZATIONNAME: {{ cookiecutter.organization }}
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: ./{{ cookiecutter.name }}/Resources/Configuration/Debug.xcconfig
  Release: ./{{ cookiecutter.name }}/Resources/Configuration/Release.xcconfig
settings:
  base:
    VERSIONING_SYSTEM: apple-generic
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: {{ cookiecutter.development_team_id }}
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
  configs:
    Debug:
      OTHER_SWIFT_FLAGS: -D DEBUG
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
targets:
  {{ cookiecutter.name | lower }}:
    type: application
    platform: iOS
    sources:
      - path: {{ cookiecutter.name }}
    scheme:
      testTargets:
        - {{ cookiecutter.name | lower }}Tests
    attributes:
      ProvisioningStyle: Automatic
      DevelopmentTeam: {{ cookiecutter.development_team_id }}
    settings:
      base:
{% if cookiecutter.ipad == "Yes" %}
        TARGETED_DEVICE_FAMILY: "1,2"
{% else %}
        TARGETED_DEVICE_FAMILY: "1"
{% endif %}
        PRODUCT_BUNDLE_IDENTIFIER: {{ cookiecutter.bundle_id }}
  {{ cookiecutter.name | lower }}Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - {{ cookiecutter.name }}
      - {{ cookiecutter.name }}Tests
    dependencies:
      - target: {{ cookiecutter.name | lower }}
    settings:
      base:
        PRODUCT_MODULE_NAME: {{ cookiecutter.name | lower }}Tests
