name: {{ cookiecutter.name }}
options:
  deploymentTarget:
    iOS: {{ cookiecutter.deployment_target }}
  developmentLanguage: ru
  knownRegions: ["ru", "Base"]
  createIntermediateGroups: true
attributes:
  ORGANIZATIONNAME: {{ cookiecutter.organization }}
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: ./{{ cookiecutter.name }}/Resources/Configuration/Debug.xcconfig
  Release: ./{{ cookiecutter.name }}/Resources/Configuration/Release.xcconfig
settings:
  base:
    VERSIONING_SYSTEM: apple-generic
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: {{ cookiecutter.development_team_id }}
  configs:
    Debug:
      OTHER_SWIFT_FLAGS: -D DEBUG
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
targets:
  {{ cookiecutter.name | lower }}:
    type: application
    platform: iOS
    sources:
      - path: {{ cookiecutter.name }}
    scheme:
      testTargets:
        - {{ cookiecutter.name | lower }}Tests
    prebuildScripts:
      - script: |
                if [ "${CONFIGURATION}" == "Debug" ]; then
                  if which mint >/dev/null; then
                    make swiftgen
                  fi
                fi
        name: SwiftGen
      - script: |
                if [ "${CONFIGURATION}" == "Debug" ]; then
                  if which mint >/dev/null; then
                    make fmt
                  fi
                fi
        name: SwiftFormat
    attributes:
      ProvisioningStyle: Manual
      DevelopmentTeam: {{ cookiecutter.development_team_id }}
    settings:
      base:
{% if cookiecutter.ipad == "Yes" %}
        TARGETED_DEVICE_FAMILY: "1,2"
{% else %}
        TARGETED_DEVICE_FAMILY: "1"
{% endif %}
        PRODUCT_BUNDLE_IDENTIFIER: {{ cookiecutter.bundle_id }}
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
          PROVISIONING_PROFILE_SPECIFIER: match Development {{ cookiecutter.bundle_id }}
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: match AppStore {{ cookiecutter.bundle_id }}
  {{ cookiecutter.name | lower }}Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - {{ cookiecutter.name }}
      - {{ cookiecutter.name }}Tests
    dependencies:
      - target: {{ cookiecutter.name | lower }}
