name: {{ cookiecutter.name }}
options:
  bundleIdPrefix: {{ cookiecutter.bundle_prefix }}
  deploymentTarget:
    iOS: {{ cookiecutter.deployment_target }}
configs:
  Debug: debug
  Internal: release
  Release: release
settings:
  base:
    VERSIONING_SYSTEM: apple-generic
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 4.2
    DEVELOPMENT_TEAM: {{ cookiecutter.development_team_id }}
  configs:
    Debug:
      OTHER_SWIFT_FLAGS: -D DEBUG
    Internal:
      OTHER_SWIFT_FLAGS: -D INTERNAL
    Release:
      OTHER_SWIFT_FLAGS: -D RELEASE
targets:
  {{ cookiecutter.name | lower }}:
    type: application
    platform: iOS
    sources:
      - path: {{ cookiecutter.name }}
    dependencies:
      - carthage: ObjcExceptionBridging
      - carthage: XCGLogger
    scheme:
      testTargets:
        - {{ cookiecutter.name | lower }}Tests
    prebuildScripts:
      - script: |
                if [ "${CONFIGURATION}" == "Debug" ]; then
                  if which mint >/dev/null; then
                    mint run swiftgen/swiftgen
                  fi
                fi
        name: SwiftGen
      - script: |
                if [ "${CONFIGURATION}" == "Debug" ]; then
                  if which mint >/dev/null; then
                    mint run realm/swiftlint
                  fi
                fi
        name: SwiftLint
    attributes:
      ProvisioningStyle: Manual
      DevelopmentTeam: {{ cookiecutter.development_team_id }}
    settings:
      base:
{% if cookiecutter.ipad == "Yes" %}
        TARGETED_DEVICE_FAMILY: "1,2"
{% else %}
        TARGETED_DEVICE_FAMILY: "1"
{% endif %}
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
          PROVISIONING_PROFILE_SPECIFIER: match Development {{ cookiecutter.bundle_prefix }}.{{ cookiecutter.name | lower }}
        Internal:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: match AppStore {{ cookiecutter.bundle_prefix }}.{{ cookiecutter.name | lower }}
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: match AppStore {{ cookiecutter.bundle_prefix }}.{{ cookiecutter.name | lower }}
  {{ cookiecutter.name | lower }}Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [{{ cookiecutter.name }}Tests]
