name: {{ cookiecutter.name }}
options:
  bundleIdPrefix: {{ cookiecutter.bundle }}
  deploymentTarget:
    iOS: {{ cookiecutter.deployment_target }}
configs:
  Debug: debug
  Internal: release
  Release: release
settings:
  base:
    VERSIONING_SYSTEM: apple-generic
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 4.2
  configs:
    Debug:
      OTHER_SWIFT_FLAGS: -D DEBUG
    Internal:
      OTHER_SWIFT_FLAGS: -D INTERNAL
    Release:
      OTHER_SWIFT_FLAGS: -D RELEASE
targets:
  {{ cookiecutter.name }}:
    type: application
    platform: iOS
    sources: [{{ cookiecutter.name }}]
    scheme: {}
    prebuildScripts:
      - script: |
                if [ "${CONFIGURATION}" == "Debug" ]; then
                  mint run swiftgen/swiftgen
                fi
        name: SwiftGen
      - script: |
                if [ "${CONFIGURATION}" == "Debug" ]; then
                  mint run realm/swiftlint
                fi
        name: SwiftLint
