language: objective-c
osx_image: xcode11.2
xcode_sdk: iphoneos11.0
env:
  - MINT_PATH="~/mint_cache"
cache:
  bundler: true
  directories:
    - $MINT_PATH
    - Project/Carthage/Build
script:
  - brew install cookiecutter mint
  - cookiecutter --no-input -f .
  - cd Project
  - make test
