language: objective-c
osx_image: xcode10
xcode_sdk: iphoneos11.0
env:
  - MINT_PATH="~/mint_cache"
cache:
  bundler: true
  directories:
    - $MINT_PATH
    - Project/Carthage/Build
script:
  - brew install cookiecutter mint gpg pwgen
  - cookiecutter --no-input -f .
  - cd Project
  - gpg --pinentry-mode loopback --passphrase $(pbpaste) ./Project/Resources/Configuration.plist.gpg
  - bundle install
  - bundle exec fastlane test
