#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

build_number = ENV['BITRISE_BUILD_NUMBER']
deploy_dir = ENV['BITRISE_DEPLOY_DIR']
api_key = "fastlane/api-key.json"

platform :ios do

  desc 'Create a new application on the developer portal'
  lane :create do
    produce
    match(
      type: "development",
      clone_branch_directly: false,
      api_key_path: api_key,
    )
    match(
      type: "appstore",
      clone_branch_directly: false,
      api_key_path: api_key,
    )
  end

  desc 'Register devices on apple portal'
  lane :register do
    register_devices(
      devices_file: "./fastlane/devices.txt",
      api_key_path: api_key,
    )
    match(
      type: "development",
      force_for_new_devices: true,
      api_key_path: api_key,
    )
  end

  desc 'Perform test checks'
  lane :test do
    scan(
      output_directory: deploy_dir,
      cloned_source_packages_path: ".cache/spm",
    )
  end

  desc 'Deploy a build for beta testing'
  lane :internal do
    match(
      type: "appstore",
      readonly: true
    )

    add_badge(
      glob: '/{{ cookiecutter.name }}/**/*.appiconset/*.{png, PNG}'
    )

    increment_build_number(
      build_number: build_number
    )

    gym(
      export_method: 'app-store',
      configuration: 'Release',
      cloned_source_packages_path: ".cache/spm",
    )

    pilot(
      api_key_path: api_key,
      distribute_external: true,
      beta_app_feedback_email: '{{ cookiecutter.apple_id }}',
      beta_app_description: 'Beta build for testing',
      changelog: 'Fixes and improvements',
      groups: 'Beta',
    )

  end

  desc 'Deploy a release build'
  lane :release do
  end
end
