#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

build_number = ENV['BITRISE_BUILD_NUMBER']
deploy_dir = ENV['BITRISE_DEPLOY_DIR']

platform :ios do

  desc 'Create a new application on the developer portal'
  lane :create do
    produce
    match(type: "development")
    match(type: "appstore")
  end

  desc 'Register devices on apple portal'
  lane :register do
    register_devices(
      devices_file: "./fastlane/devices.txt"
    )
    match(
      type: "development",
      force_for_new_devices: true
    )
  end

  desc 'Perform test checks'
  lane :test do
    bootstrap_carthage
    scan(
      output_directory: deploy_dir,
    )
  end

  desc 'Deploy a build for beta testing'
  lane :internal do
    match(
      type: "appstore",
      readonly: true
    )

    bootstrap_carthage

    add_badge(
      glob: '/{{ cookiecutter.name }}/**/*.appiconset/*.{png, PNG}'
    )

    increment_build_number(
      build_number: build_number
    )

    gym(
      export_method: 'app-store',
      configuration: 'Internal'
    )

    pilot(
      distribute_external: true,
      beta_app_feedback_email: '{{ cookiecutter.apple_id }}',
      beta_app_description: 'Beta build for testing',
      wait_for_uploaded_build: true,
      changelog: 'Fixes and improvements',
      groups: 'Beta',
    )

  end

  desc 'Deploy a build for the external beta testing'
  lane :external do
  end

  desc 'Deploy a release build'
  lane :release do
  end

  private_lane :bootstrap_carthage do
    carthage(
      platform: 'iOS',
      cache_builds: true,
      use_binaries: false,
    )
  end
end
