name: "Build project and run tests"

on: [push]

jobs:
  test:
    runs-on: macos-latest
    env:
      MINT_PATH: "~/mint_cache"

    steps:
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_12.0.app/Contents/Developer
        xcodebuild -version

    - uses: actions/checkout@v1

    - name: Cache Mint
      id: cache-mint
      uses: actions/cache@v1
      with:
        path: ~/mint_cache
        key: cache

    - name: Generate project and run tests
      run: |
        brew install cookiecutter mint
        cookiecutter --no-input -f .
        cd Project
        mint bootstrap
        make test
