name: "Build project and run tests"

on: [push]

jobs:
  test:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v1

      - name: Generate project and run tests
        run: |
          brew install cookiecutter mise xcbeautify &&
          mise settings set experimental true &&
          mise activate --shims &&
          cookiecutter --no-input -f . &&
          cd Project &&
          mise install &&
          xcodebuild -project Project.xcodeproj -scheme project -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' test | xcbeautify
