name: "Build project and run tests"

on: [push]

jobs:
  test:
    runs-on: macos-14
    env:
      MINT_PATH: "~/mint_cache"

    steps:
      - uses: actions/checkout@v1

      - name: Generate project and run tests
        run: |
          export PATH=~/.rbenv/shims:"$PATH"

          brew install cookiecutter rbenv mint fastlane &&
          rbenv install 3.0.6 &&
          cookiecutter --no-input -f . &&
          cd Project &&
          fastlane scan
